"""
CBWTR Query Studio — Streamlit frontend
Run:  streamlit run app.py

No live database: tables are loaded from spreadsheets in data/excel and queried
locally with DuckDB. SQL is generated by Qwen 2.5 Coder (Ollama) as T-SQL and
transpiled to DuckDB before execution.
"""

import streamlit as st
import time
import os
import csv
import getpass

st.set_page_config(
    page_title="CBWTR Query Studio",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

from config import settings
from core import db, static_schema, embedder
from core.llm import check_ollama
from core.pipeline import run_query_pipeline
from core.schema import schema_summary

# CSS 
st.markdown("""
<style>
[data-testid="stSidebar"] { min-width: 330px; max-width: 400px; }
.badge-ok  { background:#1a4731; color:#3fb950; border-radius:4px;
             padding:2px 8px; font-size:.75rem; font-weight:600; }
.badge-err { background:#4a1f1f; color:#f85149; border-radius:4px;
             padding:2px 8px; font-size:.75rem; font-weight:600; }
.pill      { display:inline-block; background:#13294b; color:#6cb6ff;
             border:1px solid #1f6feb; border-radius:12px;
             padding:2px 10px; margin:2px 4px 2px 0; font-size:.78rem; }
</style>
""", unsafe_allow_html=True)

# Session state 
for k, v in {
    "last_result":    None,
    "history":        [],
    "extra_glossary": "",
    "table_select":   [],
    "question":       "",
}.items():
    if k not in st.session_state:
        st.session_state[k] = v

ALL_TABLES = [r["table"] for r in db.load_report() if not r["error"]]


# Embedding index (loads MiniLM + builds/loads Chroma; cached once)
@st.cache_resource(show_spinner="Preparing semantic table search…")
def _init_embedder() -> str:
    try:
        status = embedder.initialise(static_schema.COLUMN_META)
        return True, status
    except Exception as exc:          # noqa: BLE001
        return False, str(exc)



def log_history_to_csv(record, filename="query_history.csv"):
    """Appends a dictionary record to a CSV file."""
    file_exists = os.path.isfile(filename)
    fieldnames = ["date", "time", "user", "question", "sql", "rows", "error"]
    with open(filename, mode='a', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        if not file_exists:
            writer.writeheader()
        writer.writerow(record)

#  SIDEBAR
with st.sidebar:
    st.title("⚙️ Configuration")

    
    # Data & Model Status 
    st.subheader("Data & Model")
    
    report = db.load_report()
    loaded   = [r for r in report if not r["error"]]
    missing  = [r for r in report if r["error"]]
    total_rows = sum(r["rows"] for r in loaded)
    
    st.caption(f"{len(loaded)}/{len(report)} tables loaded")
    
    if missing:
        with st.expander(f"⚠️ {len(missing)} table(s) not loaded", expanded=False):
            for r in missing:
                st.write(f"`{r['table']}` — {r['error']}")
            st.caption(f"Drop spreadsheets in: `{settings.EXCEL_DIR}`")

    action_col1, action_col2 = st.columns(2)

    with action_col1:
        if st.button("Reload data", use_container_width=True):
            with st.spinner("Reloading…"):
                db.reload()
            st.rerun()

    with action_col2:
        if st.button("Check model", use_container_width=True):
            with st.spinner("Checking…"):
                ok, msg = check_ollama()
            if ok:
                st.success(f"Ready: `{msg}`")
            else:
                st.error(msg)

    st.divider()

    #Table selector 
    st.subheader("Tables in context")
    st.caption(f"{len(ALL_TABLES)} tables available")

    def _select_all():
        st.session_state["table_multiselect"] = list(ALL_TABLES)

    def _clear_all():
        st.session_state["table_multiselect"] = []

    def _apply_suggested():
        st.session_state["table_multiselect"] = [
            t for t in st.session_state.suggested_tables if t in ALL_TABLES
        ]
    
    
    c1, c2 = st.columns(2)
    c1.button("All",   width='stretch', on_click=_select_all)
    c2.button("Clear", width='stretch', on_click=_clear_all)

    selected_tables: list[str] = st.multiselect(
        "Tables",
        options=ALL_TABLES,
        placeholder="Search and select tables…",
        label_visibility="collapsed",
        key="table_multiselect",
    )

    if selected_tables:
        total_cols = sum(len(static_schema.SCHEMA[t]) for t in selected_tables)
        st.caption(f"{len(selected_tables)} table(s) · {total_cols} columns in prompt")

    st.divider()

    # Extra glossary 
    with st.expander("Extra glossary hints", expanded=False):
        st.caption(
            "Add any extra hints here (e.g. country code mappings, business rules)."
        )
        st.session_state.extra_glossary = st.text_area(
            "Extra glossary",
            value=st.session_state.extra_glossary,
            height=160,
            placeholder="e.g.\n  country code 101 = India\n  STR threshold = 500000 INR",
            label_visibility="collapsed",
        )

    # History 
    if st.session_state.history:
        st.divider()
        st.subheader("History")
        for h in reversed(st.session_state.history[-8:]):
            icon = "✅" if not h["error"] else "❌"
            with st.expander(f"{icon} {h['question'][:42]}…", expanded=False):
                st.caption(h["ts"])
                if h["sql"]:
                    st.code(h["sql"], language="sql")
                if h["error"]:
                    st.error(h["error"])


###########
#  MAIN
###########
st.title("🔍 CBWTR Query Studio")
st.caption("Ask — SQL is generated and run locally")

# Standard Questions 
STANDARD_QUESTIONS = [
    "Show me all wire transfers where the amount in INR is more than 50 lakhs in the last 90 days,which is origineted from china,uae,usa, to india",
    "List all transactions where the sender bank BIC is not available or is blank",
    "Show me all entities whose KYC has not been refreshed in the last 2 years",
    "Give me all companies where UBO details are not available and their risk level is high",
    "Give me all GOS records where the attempted transaction flag is yes and status is still pending"
]

def _set_question(q: str):
    st.session_state["question"] = q

label_col, icon_col = st.columns([15, 1], vertical_alignment="bottom")

with icon_col:
    with st.popover("💡", help="Standard questions", use_container_width=True):
        st.markdown("**Quick Questions**")
        for sq in STANDARD_QUESTIONS:
            st.button(sq, on_click=_set_question, args=(sq,), width='stretch')
question = st.text_area(
    "Your question",
    key="question",
    placeholder=(
        "e.g.  Show all transactions above 10 lakh INR from the last 30 days\n"
        "       Which sender banks sent the most wires to high-risk countries?\n"
        "       List top 10 beneficiaries by total amount received"
    ),
    height=100,
)

# Semantic table suggestions (reactive)
scored = []
if question.strip():
    with st.spinner("Initialising search index (first time only)…"):
        _embed_ok, _embed_msg = _init_embedder()
    if _embed_ok:
        try:
            scored = embedder.suggest_tables_with_scores(
                question.strip(), max_tables=len(ALL_TABLES)
            )
            max_score = max((s for _, s in scored), default=1.0) or 1.0
            scored = [
                (t, s) for t, s in scored
                if t in ALL_TABLES and s >= max_score / 2
            ][:5]
        except Exception:              # noqa: BLE001
            scored = []
 
if scored:
    # Save to session state BEFORE the button renders so _apply_suggested
    # always has a valid list (fixes the KeyError on very first click)
    st.session_state["suggested_tables"] = [t for t, _ in scored]
    sug_col, btn_col = st.columns([4, 1])
    with sug_col:
        pills = " ".join(f"<span class='pill'>{t}</span>" for t in st.session_state["suggested_tables"])
        st.markdown(f"**Suggested tables:** {pills}", unsafe_allow_html=True)
    with btn_col:
        st.button(
            "✦ Use suggested",
            width='stretch',
            on_click=_apply_suggested,
        )
    with st.expander("Confidence", expanded=False):
        max_score = max((s for _, s in scored), default=1.0) or 1.0
        for t, s in scored:
            st.write(f"`{t}`")
            st.progress(min(max(s / max_score, 0.0), 1.0))


 
btn_col, hint_col = st.columns([1, 4])
run_clicked = btn_col.button("▶  Run", type="primary", width='stretch')

if not selected_tables:
    hint_col.warning("Select at least one table in the sidebar.")

# Execute 
if run_clicked and question.strip() and selected_tables:
    with st.status("Generating SQL…", expanded=True) as status_box:
        st.write("Waiting for response..")
        t0 = time.time()

        result = run_query_pipeline(
            question=question.strip(),
            selected_tables=selected_tables,
            extra_glossary=st.session_state.extra_glossary,
        )

        elapsed = time.time() - t0

        for ve in result.validation_errors:
            st.write(f"⚠️ {ve}")

        if result.error:
            status_box.update(label="Failed", state="error", expanded=True)
        else:
            status_box.update(
                label=f"Done · {elapsed:.1f}s · {len(result.dataframe)} rows · {result.attempts} attempt(s)",
                state="complete", expanded=False,
            )

    try:
        current_user = getpass.getuser()
    except Exception:
        current_user = "unknown_user"

    history_record = {
        "date":     time.strftime("%Y-%m-%d"),
        "time":     time.strftime("%H:%M:%S"),
        "user":     current_user,
        "question": question.strip(),
        "sql":      result.sql if result.sql else "",
        "rows":     len(result.dataframe) if result.dataframe is not None else 0,
        "error":    str(result.error) if result.error else "",
    }

    st.session_state.history.append({
        "question": history_record["question"],
        "sql":      history_record["sql"],
        "rows":     history_record["rows"],
        "error":    history_record["error"],
        "ts":       history_record["time"],
    })

    try:
        log_history_to_csv(history_record)
    except Exception as e:
        st.error(f"Failed to write history to CSV: {e}")

    st.session_state.last_result = result

    if result.error:
        st.error(result.error)

    if result.sql:
        st.subheader("Generated SQL")
        st.code(result.sql, language="sql")
        st.caption(f"Attempts: {result.attempts} · {elapsed:.1f}s")

    if result.dataframe is not None:
        df = result.dataframe
        st.subheader(f"Results — {len(df):,} row(s)")
        st.download_button(
            "⬇ Download CSV",
            data=df.to_csv(index=False).encode(),
            file_name="results.csv",
            mime="text/csv",
        )
        st.dataframe(df, width='stretch', height=420)

        num_cols = df.select_dtypes(include="number").columns.tolist()
        if num_cols:
            with st.expander("Numeric summary"):
                st.dataframe(df[num_cols].describe(), width='stretch')

elif run_clicked and not question.strip():
    st.warning("Please enter a question.")

elif st.session_state.last_result and not run_clicked:
    r = st.session_state.last_result
    if r.sql:
        st.subheader("Last query")
        st.code(r.sql, language="sql")
    if r.dataframe is not None:
        st.subheader(f"Last results — {len(r.dataframe):,} row(s)")
        st.dataframe(r.dataframe, width='stretch', height=380)

st.divider()
st.caption("Read-only · MAX 500 rows · Validated & transpiled before execution .")
